version: '3'
services:
  server:
    container_name: docker-node-server
    restart: always
    build:
      context: server/
      dockerfile: Dockerfile
    ports:
    - '4000:4000'

  client:
    container_name: docker-node-client
    restart: always
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
    - '3000:3000'
    stdin_open: true
    links:
      - server

